name: Makefile CI
on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run vet
      run: make vet

    - name: Update coverage report
      uses: ncruces/go-coverage-report@v0
      with:
        report: true
        chart: true
        amend: true
      if: github.event_name == 'push'  
      continue-on-error: true
